### ISSUE TITLE
no .rock64-sdimg image

### ISSUE THREAD

**Issue by bernardoaraujor** [trecetp/meta-rock64#2]
I'm running a build with Poky and meta-openembedded set to warrior.
There's no `.rock64-sdimg` image, only `.dtb`, kernel image and compressed rootfs.

```
bernardoaraujor@edf-ci:~/yocto/build$ ls tmp/deploy/images/rock64/
core-image-base-rock64-20200127163249.rootfs.manifest       honeycomb-image-base-rock64.tar.gz
core-image-base-rock64-20200127163249.rootfs.tar.gz         honeycomb-image-base-rock64.testdata.json
core-image-base-rock64-20200127163249.testdata.json         Image
core-image-base-rock64.manifest                             Image--4.4.190-r0-rock64-20200127154225.bin
core-image-base-rock64.tar.gz                               Image-rock64.bin
core-image-base-rock64.testdata.json                        modules--4.4.190-r0-rock64-20200127154225.tgz
honeycomb-image-base-rock64-20200127154225.rootfs.manifest  modules-rock64.tgz
honeycomb-image-base-rock64-20200127154225.rootfs.tar.gz    rk3328-rock64--4.4.190-r0-rock64-20200127154225.dtb
honeycomb-image-base-rock64-20200127154225.testdata.json    rk3328-rock64.dtb
honeycomb-image-base-rock64.manifest                        rk3328-rock64-rock64.dtb
```

A `.rock64-sdimg` would be great.
This is a good reference: 
 - https://github.com/agherzan/meta-raspberrypi/blob/master/wic/sdimage-raspberrypi.wks
 - https://github.com/agherzan/meta-raspberrypi/blob/master/classes/sdcard_image-rpi.bbclass

@trecetp what's the partition layout you've been using for your SD cards?
Are these artifacts enough to boot the board?

**Comment by LE0xUL** [comment]
Hi Bernardo

The partition layout is explained in [GPT partition table]( http://opensource.rock-chips.com/wiki_Partitions) and the boot flow here: [Boot_Option](http://opensource.rock-chips.com/wiki_Boot_option)

There are several ways to boot a rockchip chip, but for this meta-layer you can use the idbloader.bin,  uboot.img and trust.img files, generated by the BSP recipes

These files, can you guide to create the recipes to generate a SD-card:
 * https://github.com/rockchip-linux/meta-rockchip/blob/yocto-next/wic/generic-gptdisk.wks.in
 * https://github.com/trecetp/balena-rock64/blob/master/layers/meta-balena-rock64/recipes-core/images/resin-image.inc

Regards

**Comment by bernardoaraujor** [comment]
I ordered a rock64 that should arrive soon.
Then I'll try to follow the links you shared, and maybe submit a PR with a wks if everything goes right.

Thanks so much!

**Comment by bernardoaraujor** [comment]
@trecetp have you ever faced this?
```
ernardo@bernardo-S451LA:~/dev/yocto/build/tmp/deploy/images/rock64$ bitbake u-boot-rockchip
Loading cache: 100% |#################################################################################################################| Time: 0:00:00
Loaded 3073 entries from dependency cache.
Parsing recipes: 100% |###############################################################################################################| Time: 0:00:00
Parsing of 2020 .bb files complete (2016 cached, 4 parsed). 3077 targets, 108 skipped, 0 masked, 0 errors.
NOTE: Resolving any missing task queue dependencies

Build Configuration:
BB_VERSION           = "1.42.0"
BUILD_SYS            = "x86_64-linux"
NATIVELSBSTRING      = "universal"
TARGET_SYS           = "aarch64-poky-linux"
MACHINE              = "rock64"
DISTRO               = "poky"
DISTRO_VERSION       = "2.7.2"
TUNE_FEATURES        = "aarch64 cortexa53 crc"
TARGET_FPU           = ""
meta                 
meta-poky            
meta-yocto-bsp       = "warrior:4edf4eb9cc86fbd4b51240fae527c1b97a7ace74"
meta-oe              
meta-python          = "warrior:a24acf94d48d635eca668ea34598c6e5c857e3f8"
meta-rock64          = "master:a55945e9e7fc597c74820938f666c5d8883812a1"
meta-tangle          
meta-honeycomb       = "master:6315af8f3dd377f6710c9d2556edf2f48cbba64a"

Initialising tasks: 100% |############################################################################################################| Time: 0:00:00
Sstate summary: Wanted 13 Found 0 Missed 13 Current 71 (0% match, 84% complete)
NOTE: Executing SetScene Tasks
NOTE: Executing RunQueue Tasks
WARNING: Exception during build_dependencies for do_configure
WARNING: Error during finalise of /home/bernardo/dev/yocto/meta-rock64/recipes-bsp/u-boot/u-boot-rockchip.bb
ERROR: Traceback (most recent call last):
  File "/home/bernardo/dev/yocto/poky/bitbake/lib/bb/fetch2/__init__.py", line 1562, in latest_revision
    return revs[key]
  File "/home/bernardo/dev/yocto/poky/bitbake/lib/bb/persist_data.py", line 50, in wrap_func
    return f(self, *args, **kwargs)
  File "/home/bernardo/dev/yocto/poky/bitbake/lib/bb/persist_data.py", line 79, in wrap_func
    return f(self, cursor, *args, **kwargs)
  File "/home/bernardo/dev/yocto/poky/bitbake/lib/bb/persist_data.py", line 165, in __getitem__
    raise KeyError(key)
KeyError: 'git:gitlab.denx.de.u-boot.custodians.u-boot-rockchip.gitu-boot-rockchip-20190920-u-boot-rockchip'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bernardo/dev/yocto/poky/bitbake/lib/bb/data_smart.py", line 413, in expandWithRefs
    s = __expand_python_regexp__.sub(varparse.python_sub, s)
  File "/home/bernardo/dev/yocto/poky/bitbake/lib/bb/data_smart.py", line 138, in python_sub
    value = utils.better_eval(codeobj, DataContext(self.d), {'d' : self.d})
  File "/home/bernardo/dev/yocto/poky/bitbake/lib/bb/utils.py", line 423, in better_eval
    return eval(source, ctx, locals)
  File "Var <do_configure>", line 1, in <module>
  File "/home/bernardo/dev/yocto/poky/meta/recipes-bsp/u-boot/u-boot.inc", line 73, in find_cfgs
    sources=src_patches(d, True)
  File "/home/bernardo/dev/yocto/poky/meta/classes/patch.bbclass", line 80, in src_patches
    return oe.patch.src_patches(d, all, expand)
  File "/home/bernardo/dev/yocto/poky/meta/lib/oe/patch.py", line 809, in src_patches
    fetch = bb.fetch2.Fetch([], d)
  File "/home/bernardo/dev/yocto/poky/bitbake/lib/bb/fetch2/__init__.py", line 1603, in __init__
    self.ud[url] = FetchData(url, d, localonly)
  File "/home/bernardo/dev/yocto/poky/bitbake/lib/bb/fetch2/__init__.py", line 1274, in __init__
    self.method.urldata_init(self, d)
  File "/home/bernardo/dev/yocto/poky/bitbake/lib/bb/fetch2/git.py", line 239, in urldata_init
    ud.revisions[name] = self.latest_revision(ud, d, name)
  File "/home/bernardo/dev/yocto/poky/bitbake/lib/bb/fetch2/__init__.py", line 1564, in latest_revision
    revs[key] = rev = self._latest_revision(ud, d, name)
  File "/home/bernardo/dev/yocto/poky/bitbake/lib/bb/fetch2/git.py", line 617, in _latest_revision
    output = self._lsremote(ud, d, "")
  File "/home/bernardo/dev/yocto/poky/bitbake/lib/bb/fetch2/git.py", line 606, in _lsremote
    output = runfetchcmd(cmd, d, True)
  File "/home/bernardo/dev/yocto/poky/bitbake/lib/bb/fetch2/__init__.py", line 886, in runfetchcmd
    raise FetchError(error_message)
bb.fetch2.FetchError: Fetcher failure: Fetch command export PSEUDO_DISABLED=1; unset _PYTHON_SYSCONFIGDATA_NAME; export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/1000/bus"; export SSH_AGENT_PID="2015"; export SSH_AUTH_SOCK="/tmp/ssh-vk0VVKNxFLTz/agent.1933"; export PATH="/home/bernardo/dev/yocto/build/tmp/sysroots-uninative/x86_64-linux/usr/bin:/home/bernardo/dev/yocto/poky/scripts:/home/bernardo/dev/yocto/build/tmp/work/rock64-poky-linux/u-boot-rockchip/1.0-r0/recipe-sysroot-native/usr/bin/aarch64-poky-linux:/home/bernardo/dev/yocto/build/tmp/work/rock64-poky-linux/u-boot-rockchip/1.0-r0/recipe-sysroot/usr/bin/crossscripts:/home/bernardo/dev/yocto/build/tmp/work/rock64-poky-linux/u-boot-rockchip/1.0-r0/recipe-sysroot-native/usr/sbin:/home/bernardo/dev/yocto/build/tmp/work/rock64-poky-linux/u-boot-rockchip/1.0-r0/recipe-sysroot-native/usr/bin:/home/bernardo/dev/yocto/build/tmp/work/rock64-poky-linux/u-boot-rockchip/1.0-r0/recipe-sysroot-native/sbin:/home/bernardo/dev/yocto/build/tmp/work/rock64-poky-linux/u-boot-rockchip/1.0-r0/recipe-sysroot-native/bin:/home/bernardo/dev/yocto/poky/bitbake/bin:/home/bernardo/dev/yocto/build/tmp/hosttools"; export HOME="/home/bernardo"; git -c core.fsyncobjectfiles=0 ls-remote https://gitlab.denx.de/u-boot/custodians/u-boot-rockchip.git  failed with exit code 128, output:
fatal: unable to access 'https://gitlab.denx.de/u-boot/custodians/u-boot-rockchip.git/': server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/bernardo/dev/yocto/poky/bitbake/bin/bitbake-worker", line 241, in child
    the_data = bb_cache.loadDataFull(fn, appends)
  File "/home/bernardo/dev/yocto/poky/bitbake/lib/bb/cache.py", line 329, in loadDataFull
    bb_data = self.load_bbfile(virtualfn, appends, virtonly=True)
  File "/home/bernardo/dev/yocto/poky/bitbake/lib/bb/cache.py", line 342, in load_bbfile
    datastores = parse_recipe(bb_data, bbfile, appends, mc)
  File "/home/bernardo/dev/yocto/poky/bitbake/lib/bb/cache.py", line 305, in parse_recipe
    bb_data = bb.parse.handle(bbfile, bb_data)
  File "/home/bernardo/dev/yocto/poky/bitbake/lib/bb/parse/__init__.py", line 107, in handle
    return h['handle'](fn, data, include)
  File "/home/bernardo/dev/yocto/poky/bitbake/lib/bb/parse/parse_py/BBHandler.py", line 144, in handle
    return ast.multi_finalize(fn, d)
  File "/home/bernardo/dev/yocto/poky/bitbake/lib/bb/parse/ast.py", line 388, in multi_finalize
    finalize(fn, d)
  File "/home/bernardo/dev/yocto/poky/bitbake/lib/bb/parse/ast.py", line 353, in finalize
    bb.parse.siggen.finalise(fn, d, variant)
  File "/home/bernardo/dev/yocto/poky/bitbake/lib/bb/siggen.py", line 141, in finalise
    taskdeps = self._build_data(fn, d)
  File "/home/bernardo/dev/yocto/poky/bitbake/lib/bb/siggen.py", line 118, in _build_data
    tasklist, gendeps, lookupcache = bb.data.generate_dependencies(d)
  File "/home/bernardo/dev/yocto/poky/bitbake/lib/bb/data.py", line 381, in generate_dependencies
    deps[task], values[task] = build_dependencies(task, keys, shelldeps, varflagsexcl, d)
  File "/home/bernardo/dev/yocto/poky/bitbake/lib/bb/data.py", line 319, in build_dependencies
    value, parsedvar = d.getVarFlag(key, "_content", False, retparser=True)
  File "/home/bernardo/dev/yocto/poky/bitbake/lib/bb/data_smart.py", line 804, in getVarFlag
    parser = self.expandWithRefs(value, cachename)
  File "/home/bernardo/dev/yocto/poky/bitbake/lib/bb/data_smart.py", line 426, in expandWithRefs
    raise ExpansionError(varname, s, exc).with_traceback(tb) from exc
  File "/home/bernardo/dev/yocto/poky/bitbake/lib/bb/data_smart.py", line 413, in expandWithRefs
    s = __expand_python_regexp__.sub(varparse.python_sub, s)
  File "/home/bernardo/dev/yocto/poky/bitbake/lib/bb/data_smart.py", line 138, in python_sub
    value = utils.better_eval(codeobj, DataContext(self.d), {'d' : self.d})
  File "/home/bernardo/dev/yocto/poky/bitbake/lib/bb/utils.py", line 423, in better_eval
    return eval(source, ctx, locals)
  File "Var <do_configure>", line 1, in <module>
  File "/home/bernardo/dev/yocto/poky/meta/recipes-bsp/u-boot/u-boot.inc", line 73, in find_cfgs
    sources=src_patches(d, True)
  File "/home/bernardo/dev/yocto/poky/meta/classes/patch.bbclass", line 80, in src_patches
    return oe.patch.src_patches(d, all, expand)
  File "/home/bernardo/dev/yocto/poky/meta/lib/oe/patch.py", line 809, in src_patches
    fetch = bb.fetch2.Fetch([], d)
  File "/home/bernardo/dev/yocto/poky/bitbake/lib/bb/fetch2/__init__.py", line 1603, in __init__
    self.ud[url] = FetchData(url, d, localonly)
  File "/home/bernardo/dev/yocto/poky/bitbake/lib/bb/fetch2/__init__.py", line 1274, in __init__
    self.method.urldata_init(self, d)
  File "/home/bernardo/dev/yocto/poky/bitbake/lib/bb/fetch2/git.py", line 239, in urldata_init
    ud.revisions[name] = self.latest_revision(ud, d, name)
  File "/home/bernardo/dev/yocto/poky/bitbake/lib/bb/fetch2/__init__.py", line 1564, in latest_revision
    revs[key] = rev = self._latest_revision(ud, d, name)
  File "/home/bernardo/dev/yocto/poky/bitbake/lib/bb/fetch2/git.py", line 617, in _latest_revision
    output = self._lsremote(ud, d, "")
  File "/home/bernardo/dev/yocto/poky/bitbake/lib/bb/fetch2/git.py", line 606, in _lsremote
    output = runfetchcmd(cmd, d, True)
  File "/home/bernardo/dev/yocto/poky/bitbake/lib/bb/fetch2/__init__.py", line 886, in runfetchcmd
    raise FetchError(error_message)
bb.data_smart.ExpansionError: Failure expanding variable do_configure, expression was     if [ -z "${UBOOT_CONFIG}" ]; then
        if [ -n "rock64-rk3328_defconfig" ]; then
            oe_runmake -C /home/bernardo/dev/yocto/build/tmp/work/rock64-poky-linux/u-boot-rockchip/1.0-r0/git O=/home/bernardo/dev/yocto/build/tmp/work/rock64-poky-linux/u-boot-rockchip/1.0-r0/build rock64-rk3328_defconfig
        else
            oe_runmake -C /home/bernardo/dev/yocto/build/tmp/work/rock64-poky-linux/u-boot-rockchip/1.0-r0/git O=/home/bernardo/dev/yocto/build/tmp/work/rock64-poky-linux/u-boot-rockchip/1.0-r0/build oldconfig
        fi
        merge_config.sh -m .config ${@" ".join(find_cfgs(d))}
        cml1_do_configure
    fi
 which triggered exception FetchError: Fetcher failure: Fetch command export PSEUDO_DISABLED=1; unset _PYTHON_SYSCONFIGDATA_NAME; export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/1000/bus"; export SSH_AGENT_PID="2015"; export SSH_AUTH_SOCK="/tmp/ssh-vk0VVKNxFLTz/agent.1933"; export PATH="/home/bernardo/dev/yocto/build/tmp/sysroots-uninative/x86_64-linux/usr/bin:/home/bernardo/dev/yocto/poky/scripts:/home/bernardo/dev/yocto/build/tmp/work/rock64-poky-linux/u-boot-rockchip/1.0-r0/recipe-sysroot-native/usr/bin/aarch64-poky-linux:/home/bernardo/dev/yocto/build/tmp/work/rock64-poky-linux/u-boot-rockchip/1.0-r0/recipe-sysroot/usr/bin/crossscripts:/home/bernardo/dev/yocto/build/tmp/work/rock64-poky-linux/u-boot-rockchip/1.0-r0/recipe-sysroot-native/usr/sbin:/home/bernardo/dev/yocto/build/tmp/work/rock64-poky-linux/u-boot-rockchip/1.0-r0/recipe-sysroot-native/usr/bin:/home/bernardo/dev/yocto/build/tmp/work/rock64-poky-linux/u-boot-rockchip/1.0-r0/recipe-sysroot-native/sbin:/home/bernardo/dev/yocto/build/tmp/work/rock64-poky-linux/u-boot-rockchip/1.0-r0/recipe-sysroot-native/bin:/home/bernardo/dev/yocto/poky/bitbake/bin:/home/bernardo/dev/yocto/build/tmp/hosttools"; export HOME="/home/bernardo"; git -c core.fsyncobjectfiles=0 ls-remote https://gitlab.denx.de/u-boot/custodians/u-boot-rockchip.git  failed with exit code 128, output:
fatal: unable to access 'https://gitlab.denx.de/u-boot/custodians/u-boot-rockchip.git/': server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none


ERROR: Task (/home/bernardo/dev/yocto/meta-rock64/recipes-bsp/u-boot/u-boot-rockchip.bb:do_fetch) failed with exit code '1'
NOTE: Tasks Summary: Attempted 473 tasks of which 470 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
  /home/bernardo/dev/yocto/meta-rock64/recipes-bsp/u-boot/u-boot-rockchip.bb:do_fetch
```

**Comment by bernardoaraujor** [comment]
@trecetp which recipe generates `idbloader.bin`?

**Comment by bernardoaraujor** [comment]
nevermind about the error log above... seems to be just a silly problem with gitlab´s CA infrastructure during the weekend, but it´s already working.

I did have to install `python-dev` on the development host to go around
```
| scripts/dtc/pylibfdt/libfdt_wrap.c:149:21: fatal error: Python.h: No such file or directory
| compilation terminated.
| error: command 'gcc' failed with exit status 1
| /home/bernardoaraujor/yocto/build/tmp/work/rock64-poky-linux/u-boot-rockchip/1.0-r0/git/scripts/dtc/pylibfdt/Makefile:27: recipe for target 'scripts/dtc/pylibfdt/_libfdt.so' failed
```
kind of like https://github.com/linux-sunxi/meta-sunxi/issues/224
now `u-boot-rockchip` builds just fine.

But I´m still curiouos about which recipe builds `idbloader.bin`.

**Comment by LE0xUL** [comment]
> @trecetp which recipe generates `idbloader.bin`?
[u-boot-rockchip.bb](../blob/a55945e9e7fc597c74820938f666c5d8883812a1/recipes-bsp/u-boot/u-boot-rockchip.bb#L53) see line 53

https://github.com/trecetp/meta-rock64/blob/a55945e9e7fc597c74820938f666c5d8883812a1/recipes-bsp/u-boot/u-boot-rockchip.bb#L53

**Comment by bernardoaraujor** [comment]
duh, my bad!
since I couldn't build `u-boot-rockchip` the first time I didn't realize it could be exactly the answer to my question.

my board arrived today, so I'll probably be able to do some tests this week.

Thanks again @trecetp ! closing the issue.

**Comment by LE0xUL** [comment]
> fatal: unable to access 'https://gitlab.denx.de/u-boot/custodians/u-boot-rockchip.git/': server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none

It's a certificate problem, try `sudo update-ca-certificates`

**Comment by bernardoaraujor** [comment]
hey @trecetp I was able to make some progress, but I guess I need some help again.

I'll list the steps I've followed:

Build artifacts:
```
$ bitbake u-boot-rockchip
$ bitbake rkbin
$ bitbake honeycomb-image-base
```
Create `boot.img`:
```
$ cd tmp/deploy/images/rock64/
$ dd if=/dev/zero of=boot.img bs=1M count=32
$ sudo mkfs.fat boot.img
$ mkdir tmp
$ sudo mount boot.img tmp
$ sudo cp Image tmp/
$ sudo cp rk3328-rock64.dtb tmp/
$ sudo mkdir tmp/extlinux
$ sudo bash -c "cat > tmp/extlinux/extlinux.conf" <<'EOF'
label rockchip-kernel4.4
        kernel /Image
        fdt /rk3328-rock64.dtb
        append earlyprintk console=ttyS2,115200n8 rw root=/dev/mmcblk1p7 rootwait rootfstype=ext4 init=/sbin/init
EOF
$ sudo umount tmp
```

Create `rootfs.img`:
```
$ dd if=/dev/zero of=rootfs.img bs=1M count=1700
$ sudo mkfs.ext3 rootfs.img 
$ sudo mount rootfs.img tmp/
$ sudo tar xvf honeycomb-image-base-rock64.tar.gz -C tmp/
$ sudo umount tmp
```

Flash SD (`/dev/mmcblk0`):
```
$ sudo dd if=idbloader.bin of=/dev/mmcblk0 seek=64
$ sudo dd if=uboot.img of=/dev/mmcblk0 seek=16384
$ sudo dd if=rkbin/trust.img of=/dev/mmcblk0 seek=24576
$ sudo dd if=boot.img of=/dev/mmcblk0 seek=32768
$ sudo dd if=rootfs.img of=/dev/mmcblk0 seek=262144
$ sync
```

Then, when I boot the board, it freezes on the kernel boot:
```
ID:0x805 Y
In
LPDDR3
786MHz
Bus Width=32 Col=11 Bank=8 Row=15/15 CS=2 Die Bus-Width=32 Size=4096MB
ddrconfig:7
OUT
Boot1 Release Time: Feb  2 2018 15:41:39, version: 2.46
ChipType = 0x11, 143
SdmmcInit=2 0
BootCapSize=0
UserCapSize=0MB
FwPartOffset=2000 , 0
SdmmcInit=0 0
BootCapSize=0
UserCapSize=14784MB
FwPartOffset=2000 , 0
StorageInit ok = 23239
Raw SecureMode = 0
SecureInit read PBA: 0x4
SecureInit read PBA: 0x404
SecureInit read PBA: 0x804
SecureInit read PBA: 0xc04
SecureInit read PBA: 0x1004
SecureInit ret = 0, SecureMode = 0
LoadTrustBL
No find bl30.bin
No find bl32.bin
Load uboot, ReadLba = 2000
Load OK, addr=0x200000, size=0x9cfd0
RunBL31 0x10000
NOTICE:  BL31: v1.3(debug):f947c7e
NOTICE:  BL31: Built : 09:28:45, May 31 2017
NOTICE:  BL31:Rockchip release version: v1.3
INFO:    ARM GICv2 driver initialized
INFO:    Using opteed sec cpu_context!
INFO:    boot cpu mask: 1
INFO:    plat_rockchip_pmu_init: pd status 0xe
INFO:    BL31: Initializing runtime services
WARNING: No OPTEE provided by BL2 boot loader, Booting device without OPK
ERROR:   Error initializing runtime service opteed_fast
INFO:    BL31: Preparing for EL3 exit to normal world
INFO:    Entry point address = 0x200000
INFO:    SPSR = 0x3c9


U-Boot 2019.10-rc3 (Feb 12 2020 - 21:03:27 +0000)

Model: Pine64 Rock64
DRAM:  4 GiB
MMC:   rksdmmc@ff500000: 1, rksdmmc@ff520000: 0
Loading Environment from MMC... *** Warning - bad CRC, using default envt

In:    serial@ff130000
Out:   serial@ff130000
Err:   serial@ff130000
Model: Pine64 Rock64
Net:   
Warning: ethernet@ff540000 (eth0) using random MAC address - 7a:16:21:e73
eth0: ethernet@ff540000
Hit any key to stop autoboot:  0 
Card did not respond to voltage select!
switch to partitions #0, OK
mmc1 is current device
Scanning mmc 1:1...
Found /extlinux/extlinux.conf
Retrieving file: /extlinux/extlinux.conf
192 bytes read in 5 ms (37.1 KiB/s)
1:      rockchip-kernel4.4
Retrieving file: /Image
22904840 bytes read in 1016 ms (21.5 MiB/s)
append: earlyprintk console=ttyS2,115200n8 rw root=/dev/mmcblk1p7 rootwat
Retrieving file: /rk3328-rock64.dtb
73636 bytes read in 8 ms (8.8 MiB/s)
## Flattened Device Tree blob at 01f00000
   Booting using the fdt blob at 0x1f00000
   Loading Device Tree to 00000000fcf16000, end 00000000fcf2afa3 ... OK

Starting kernel ...

ERROR:   rockchip_plat_sip_handler: unhandled SMC (0x82000003)
ERROR:   rockchip_plat_sip_handler: unhandled SMC (0x82000003)
```

I noticed that the error message `
ERROR:   rockchip_plat_sip_handler: unhandled SMC (0x82000003)` also appears when I boot `Armbian_20.02.0-rc1_Rock64_buster_legacy_4.4.210`, the difference is that Armbian finishes booting up, while my image doesn't.

**Comment by bernardoaraujor** [comment]
Solved by partitioning the SD card into 2 different partitions (mmcblk0p1 from sector 32768 to 262143 and mmcblk0p2 from sector 262144 until the end), then
```
$ sudo dd if=idbloader.bin of=/dev/mmcblk0 seek=64
$ sudo dd if=uboot.img of=/dev/mmcblk0 seek=16384
$ sudo dd if=rkbin/trust.img of=/dev/mmcblk0 seek=24576
$ sudo dd if=boot.img of=/dev/mmcblk0p1
$ sudo dd if=rootfs.img of=/dev/mmcblk0p2
$ sync
```

The contents of `extlinux.conf` had also to be fixed:
```
label rockchip-kernel4.4
        kernel /Image
        fdt /rk3328-rock64.dtb
        append earlyprintk console=ttyS2,1500000n8 rw root=/dev/mmcblk1p2 rootwait rootfstype=ext3 init=/sbin/init
```
